name: Trachtnet Update

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install German locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8

      - name: Set locale environment variables
        run: |
          echo "LANG=de_DE.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=de_DE.UTF-8" >> $GITHUB_ENV

      - name: Update Trachtnet svgs
        run: |
          just update-trachtnet

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily trachtnet update $(date)"
          git push
